language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t gbrbd/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gbrbd/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'eu-central-1'
  app: 'docker-react'
  bucket_name: 'elasticbeanstalk-eu-central-1-800962361902'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCES_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
